/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SuppliersService } from "../suppliers.service";
import { SuppliersCreateInput } from "./SuppliersCreateInput";
import { Suppliers } from "./Suppliers";
import { SuppliersFindManyArgs } from "./SuppliersFindManyArgs";
import { SuppliersWhereUniqueInput } from "./SuppliersWhereUniqueInput";
import { SuppliersUpdateInput } from "./SuppliersUpdateInput";
import { ProductsFindManyArgs } from "../../products/base/ProductsFindManyArgs";
import { Products } from "../../products/base/Products";
import { ProductsWhereUniqueInput } from "../../products/base/ProductsWhereUniqueInput";

export class SuppliersControllerBase {
  constructor(protected readonly service: SuppliersService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Suppliers })
  async createSuppliers(
    @common.Body() data: SuppliersCreateInput,
  ): Promise<Suppliers> {
    return await this.service.createSuppliers({
      data: data,
      select: {
        contactEmail: true,
        contactPhone: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Suppliers] })
  @ApiNestedQuery(SuppliersFindManyArgs)
  async suppliersItems(@common.Req() request: Request): Promise<Suppliers[]> {
    const args = plainToClass(SuppliersFindManyArgs, request.query);
    return this.service.suppliersItems({
      ...args,
      select: {
        contactEmail: true,
        contactPhone: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Suppliers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async suppliers(
    @common.Param() params: SuppliersWhereUniqueInput,
  ): Promise<Suppliers | null> {
    const result = await this.service.suppliers({
      where: params,
      select: {
        contactEmail: true,
        contactPhone: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`,
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Suppliers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSuppliers(
    @common.Param() params: SuppliersWhereUniqueInput,
    @common.Body() data: SuppliersUpdateInput,
  ): Promise<Suppliers | null> {
    try {
      return await this.service.updateSuppliers({
        where: params,
        data: data,
        select: {
          contactEmail: true,
          contactPhone: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`,
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Suppliers })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSuppliers(
    @common.Param() params: SuppliersWhereUniqueInput,
  ): Promise<Suppliers | null> {
    try {
      return await this.service.deleteSuppliers({
        where: params,
        select: {
          contactEmail: true,
          contactPhone: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`,
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/productsItems")
  @ApiNestedQuery(ProductsFindManyArgs)
  async findProductsItems(
    @common.Req() request: Request,
    @common.Param() params: SuppliersWhereUniqueInput
  ): Promise<Products[]> {
    const query = plainToClass(ProductsFindManyArgs, request.query);
    const results = await this.service.findProductsItems(params.id, {
      ...query,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,
        price: true,
        quantity: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productsItems")
  async connectProductsItems(
    @common.Param() params: SuppliersWhereUniqueInput,
    @common.Body() body: ProductsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productsItems: {
        connect: body,
      },
    };
    await this.service.updateSuppliers({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productsItems")
  async updateProductsItems(
    @common.Param() params: SuppliersWhereUniqueInput,
    @common.Body() body: ProductsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productsItems: {
        set: body,
      },
    };
    await this.service.updateSuppliers({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productsItems")
  async disconnectProductsItems(
    @common.Param() params: SuppliersWhereUniqueInput,
    @common.Body() body: ProductsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productsItems: {
        disconnect: body,
      },
    };
    await this.service.updateSuppliers({
      where: params,
      data,
      select: { id: true },
    });
  }
}
